// <auto-generated />
namespace Community.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_addressSpace : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_addressSpace));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201202582_added_addressSpace"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
