// <auto-generated />
namespace Community.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class gfdf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gfdf));
        
        string IMigrationMetadata.Id
        {
            get { return "201410201010185_gfdf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
